[onlynoise]
image = "docker.rubedo.cloud/onlynoise:latest"
public = "onlynoise.rubedo.cloud @ 8080"
envs = "MONGO=mongo"
watchtower = true

[onlynoise-push]
image = "docker.rubedo.cloud/onlynoise-push:latest"
envs = "MONGO=mongo"
networks = ["traefik"]
doppler = true
watchtower = true

[mongo]
image = "mongo:latest"
command = "mongod --quiet"
volumes = [
    "./db:/data/db",
    "./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
]
envs = "MONGO_INITDB_DATABASE=ondb"
networks = ["traefik"]
watchtower = true