[onlynoise]
image = "docker.rubedo.cloud/onlynoise:latest"
public = "onlynoise.rubedo.cloud @ 8080"
envs = "MONGO=mongo"

[onlynoise-realtime]
image = "docker.rubedo.cloud/onlynoise-realtime:latest"
public = "onlynoise.rubedo.cloud/realtime @ 8765"
envs = "MONGO=mongo"

[onlynoise-push]
image = "docker.rubedo.cloud/onlynoise-push:latest"
envs = "MONGO=mongo"
networks = ["traefik"]
doppler = true

[mongo]
image = "mongo:latest"
volumes = [
    "./db:/data/db",
    "./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
]
envs = "MONGO_INITDB_DATABASE=ondb"
networks = ["traefik"]